

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Build'
  displayName: 'Build the web application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      name: 'Default'

    steps:
    # Step 1: Use the specified version of .NET Core SDK
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk 6.x'
      inputs:
        version: 6.x

    # Step 2: Restore project dependencies
    - task: DotNetCoreCLI@2
      displayName: 'Restore project dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    # Step 3: Build the project using the specified build configuration
    - task: DotNetCoreCLI@2
      displayName: 'Build the project - $(buildConfiguration)'
      inputs:
        command: 'build'
        arguments: '--no-restore --configuration $(buildConfiguration)'
        projects: '**/*.csproj'     
        
    - task: DotNetCoreCLI@2
      displayName: 'Publish the project - $(buildConfiguration)'
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        publishWebProjects: false
        arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop

- stage: 'Deploy'
  displayName: 'Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      name: 'Default'
    environment: SindibadEnv
    variables:
    - group: Sindibad
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource-management-CodeHub'
              appName: '$(WebAppName)'
              appType: webAppLinux
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/sindibad.Web.zip'

          - task: AzureFunctionApp@1
            displayName: 'Azure Function Deploy: sindibad.function.app'
            inputs:
              azureSubscription: 'Resource-management-CodeHub'
              appType: functionApp
              appName: '$(FunctionAppName)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/sindibad.function.app.zip'
              runtimeStack: DOTNET|6.0
              startUpCommand: 'func azure functionapp publish $(functionAppName) --no-bundler'
          - task: AzureAppServiceSettings@1
            displayName: 'Update web app settings'
            inputs:
              azureSubscription: 'Resource-management-CodeHub'
              appName: $(WebAppName)
              resourceGroupName: $(ResourceGroupName)
              appSettings: |
                [
                  {
                    "name": "SandibadFunctionAppUrl",
                    "value": "https://$(functionAppName).azurewebsites.net/api/HttpFunction",
                    "slotSetting": false
                  }
                ]